### ISSUE TITLE
adding co-factor makes the mapping button non-functional

### ISSUE THREAD

**Issue by squirrelB** [genenetwork/genenetwork2#403]
Hi. Beni again. Sorry to the bearer of another issue. The usual GEMMA is now working fine. But when I add a covariate, the "compute" button for both GEMMA and rQTL now ends up doing nothing. Adding a covariate and mapping was working well back in March/April.

**Comment by zsloan** [comment]
Thanks for pointing this out. It seems that this was introduced a few days
ago when I was trying to fix an issue where everything was opening two tabs
from the trait page (and the thing I did to fix it seems to have somehow
caused issues with submitting after adding a cofactor for unknown reasons).
After looking into the issue, I found out that apparently the double
submission thing is a Chrome specific issue that was introduced a few
months ago, so I'm just going to undo that change.

It should be working again now.

**Comment by squirrelB** [comment]
Still not working for me on Safari. I'll give it a try tomorrow on a Chrome. It maps fine without a cofactor.

**Comment by zsloan** [comment]
You might need to clear your cache, because the change was to javascript.

**Comment by zsloan** [comment]
This should be fixed now.
